services:
  - type: web
    name: chillamp-selector
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.app:app --bind 0.0.0.0:$PORT
    plan: free
    envVars:
  - key: FLASK_ENV
    value: production
  - key: FLASK_DEBUG
    value: "0"
