services:
  - type: web
    name: chillamp-selector
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: startCommand: gunicorn backend.app:app --bind 0.0.0.0:$PORT
    plan: free
