# base_bassistes.py — 101 bassistes uniques triés par nom

base_bassistes = {
    "Alibo Michel": {"caractere": "Son fluide et chantant, très mélodique avec une attaque douce. attaque", "reglages_effets": {}},
    "Baroux Manu": {"caractere": "Son chaud et rond, très adapté au groove soul/funk. rondeur", "reglages_effets": {}},
    "Beggs Nick": {"caractere": "Son futuriste et texturé, adapté au rock progressif. claquant", "reglages_effets": {}},
    "Benjelloun Michaël": {"caractere": "Son discret et précis, adapté à la variété française. rondeur", "reglages_effets": {}},
    "Biyong Franck": {"caractere": "Son énergique et nerveux, influencé par l’afrobeat. punch", "reglages_effets": {}},
    "Bisello Jean": {"caractere": "Son équilibré et chaud, idéal pour les formations jazz. rondeur", "reglages_effets": {}},
    "Bogert Tim": {"caractere": "Son gras et agressif avec un growl très présent. growl", "reglages_effets": {}},
    "Bona Richard": {"caractere": "Son chantant et soyeux, très expressif en solo. rondeur", "reglages_effets": {}},
    "Bruce Jack": {"caractere": "Son bluesy et saturé avec beaucoup de médiums. growl", "reglages_effets": {}},
    "Bussonnet Philippe": {"caractere": "Son massif et riche, puissant dans les bas-médiums, avec une grande dynamique. punch", "reglages_effets": {}},
    "Cokelaere Laurent": {"caractere": "Son percutant et dynamique, parfait pour la scène rock. attaque", "reglages_effets": {}},
    "Collins Bootsy": {"caractere": "Son exubérant et saturé avec une couleur funk très marquée. growl", "reglages_effets": {}},
    "Commerford Tim": {"caractere": "Son lourd, compressé et incisif, typé rock alternatif. punch", "reglages_effets": {}},
    "De Angelis Victoria": {"caractere": "Son garage rock avec une attaque très franche. attaque", "reglages_effets": {}},
    "Deacon John": {"caractere": "Son chaud, rond, mélodique, très pop rock. rondeur", "reglages_effets": {}},
    "Deal Kim": {"caractere": "Son brut et minimaliste, typique du lo-fi. punch", "reglages_effets": {}},
    "Dirnt Mike": {"caractere": "Son rapide, agressif et précis, parfait pour le punk. attaque", "reglages_effets": {}},
    "Dorsey Gail Ann": {"caractere": "Son moelleux, articulé et expressif. rondeur", "reglages_effets": {}},
    "Dupont Fred": {"caractere": "Son rock massif et tendu. punch", "reglages_effets": {}},
    "Durham Laura Lee": {"caractere": "Son moelleux et vintage, très groove et pop psychédélique. rondeur", "reglages_effets": {}},
    "East Nathan": {"caractere": "Son studio propre, équilibré et passe-partout. rondeur", "reglages_effets": {}},
    "Entwistle John": {"caractere": "Son articulé, rapide et en avant. attaque", "reglages_effets": {}},
    "Feraud Hadrien": {"caractere": "Son brillant, moderne et ultra défini. claquant", "reglages_effets": {}},
    "Fiszman Nicolas": {"caractere": "Son polyvalent et toujours bien intégré au mix. rondeur", "reglages_effets": {}},
    "Fisher Norwood": {"caractere": "Son saturé et funky avec un grain très original. growl", "reglages_effets": {}},
    "Flea": {"caractere": "Son explosif et claquant en slap. claquant", "reglages_effets": {}},
    "Glover Roger": {"caractere": "Son massif et chaud, avec une belle assise grave. punch", "reglages_effets": {}},
    "Gordon Mike": {"caractere": "Son souple et organique, parfait pour le jam. rondeur", "reglages_effets": {}},
    "Graham Larry": {"caractere": "Son slap puissant et claquant, pionnier du funk. claquant", "reglages_effets": {}},
    "Harris Steve": {"caractere": "Son tranchant et rapide au médiator. claquant", "reglages_effets": {}},
    "Hellborg Jonas": {"caractere": "Son libre, texturé et très expressif. growl", "reglages_effets": {}},
    "Hoppus Mark": {"caractere": "Son pop-punk rapide et efficace. attaque", "reglages_effets": {}},
    "Hook Peter": {"caractere": "Son lead médium très mélodique. claquant", "reglages_effets": {}},
    "Hurley Sean": {"caractere": "Son studio, doux et très bien posé. rondeur", "reglages_effets": {}},
    "Jamerson James": {"caractere": "Son Motown rond et glissant. rondeur", "reglages_effets": {}},
    "Jones Darryl": {"caractere": "Son stable et moderne, très ancré dans les graves. punch", "reglages_effets": {}},
    "Jones John Paul": {"caractere": "Son grave, précis et organique. rondeur", "reglages_effets": {}},
    "Kajdan Jean-Michel": {"caractere": "Son clair et articulé avec un excellent contrôle dynamique. claquant", "reglages_effets": {}},
    "Kanal Tony": {"caractere": "Son clair et efficace, très pop/rock/ska. punch", "reglages_effets": {}},
    "Kaye Carol": {"caractere": "Son studio défini, au médiator sec. attaque", "reglages_effets": {}},
    "Kilmister Lemmy": {"caractere": "Son ultra saturé et agressif. growl", "reglages_effets": {}},
    "Kumalo Bakithi": {"caractere": "Son fluide, fretless et africain. rondeur", "reglages_effets": {}},
    "Labaye Romain": {"caractere": "Son précis, moderne et souple, très défini dans le registre grave. claquant", "reglages_effets": {}},
    "Lee Geddy": {"caractere": "Son claquant, médium très présent et typé prog. claquant", "reglages_effets": {}},
    "Lee Will": {"caractere": "Son polyvalent, studio, précis et musical. rondeur", "reglages_effets": {}},
    "Lesh Phil": {"caractere": "Son libre, improvisé, organique, idéal pour les jams longs. growl", "reglages_effets": {}},
    "Levin Tony": {"caractere": "Son profond et texturé, souvent expérimental. growl", "reglages_effets": {}},
    "Lynott Phil": {"caractere": "Son chaud et simple, souvent en soutien des lignes vocales. rondeur", "reglages_effets": {}},
    "Maby Graham": {"caractere": "Son mélodique et élégant, parfaitement intégré aux arrangements. rondeur", "reglages_effets": {}},
    "Manring Michael": {"caractere": "Son poétique, très ambiant, avec usage de microtonalités et fretless. growl", "reglages_effets": {}},
    "McCartney Paul": {"caractere": "Son mélodique, rond et vintage. rondeur", "reglages_effets": {}},
    "McKagan Duff": {"caractere": "Son rock incisif avec une grosse attaque. attaque", "reglages_effets": {}},
    "McVie John": {"caractere": "Son solide et discret, très ancré dans le groove de Fleetwood Mac. rondeur", "reglages_effets": {}},
    "Mbappé Etienne": {"caractere": "Son velouté, très chantant, avec une touche africaine subtile. rondeur", "reglages_effets": {}},
    "Mendez Martin": {"caractere": "Son sombre, puissant et articulé. growl", "reglages_effets": {}},
    "Mendel Nate": {"caractere": "Son solide et efficace pour le rock US. punch", "reglages_effets": {}},
    "Mienniel Jocelyn": {"caractere": "Son électro-acoustique, texturé, très expérimental. growl", "reglages_effets": {}},
    "Miller Marcus": {"caractere": "Son claquant, slappé, très net et articulé. claquant", "reglages_effets": {}},
    "Morel Jean-Philippe": {"caractere": "Son contemporain, sobre, au service du collectif jazz. rondeur", "reglages_effets": {}},
    "Moutin Louis": {"caractere": "Son jazz vif et organique, entre contrebasse et électrique. attaque", "reglages_effets": {}},
    "Mulot Pascal": {"caractere": "Son très tranchant, rapide et technique, pour le metal et le shred. claquant", "reglages_effets": {}},
    "Myung John": {"caractere": "Son précis, rapide, très compressé, pour les architectures prog. punch", "reglages_effets": {}},
    "Ndegeocello Meshell": {"caractere": "Son profond, introspectif, très texturé. rondeur", "reglages_effets": {}},
    "Newsted Jason": {"caractere": "Son agressif, au médiator, parfaitement taillé pour le thrash metal. growl", "reglages_effets": {}},
    "Paganotti Bernard": {"caractere": "Son lourd et structuré, typé zeuhl/jazz-rock français. punch", "reglages_effets": {}},
    "Palladino Pino": {"caractere": "Son souple et fretless très expressif. rondeur", "reglages_effets": {}},
    "Pastorius Jaco": {"caractere": "Son légendaire fretless, très chantant. growl", "reglages_effets": {}},
    "Prestia Rocco": {"caractere": "Son staccato hyper précis, funky, rythmique et sec. punch", "reglages_effets": {}},
    "Ramone Dee Dee": {"caractere": "Son brut et rapide, ultra minimaliste pour le punk. attaque", "reglages_effets": {}},
    "Rossi Stéphan": {"caractere": "Son équilibré et pro, très adapté à la variété et au studio. rondeur", "reglages_effets": {}},
    "Rostand Alexis": {"caractere": "Son dansant et funky, moderne et pop à la française. claquant", "reglages_effets": {}},
    "Rutherford Mike": {"caractere": "Son progressif discret, toujours efficace dans le groove. rondeur", "reglages_effets": {}},
    "Sabal-Lecco Armand": {"caractere": "Son puissant, chaud et fluide, avec beaucoup de nuances africaines. punch", "reglages_effets": {}},
    "Sklar Leland": {"caractere": "Son doux, rond, ultra propre, typique du studio US. rondeur", "reglages_effets": {}},
    "Spalding Esperanza": {"caractere": "Son jazz expressif, très lyrique, en finger ou en contrebasse. growl", "reglages_effets": {}},
    "Squire Chris": {"caractere": "Son brillant et agressif, très en avant dans le mix prog rock. claquant", "reglages_effets": {}},
    "Taylor John": {"caractere": "Son funky et dansant, très 80s et synthétique. punch", "reglages_effets": {}},
    "Texier Henri": {"caractere": "Son jazz profond, aux résonances boisées, souvent à la contrebasse. rondeur", "reglages_effets": {}},
    "Vernerey Laurent": {"caractere": "Son chaud, précis, grave bien tenu, très propre en studio live. attaque", "reglages_effets": {}},
    "Waters Roger": {"caractere": "Son simple, droit et grave, servant la narration musicale. rondeur", "reglages_effets": {}},
    "Weymouth Tina": {"caractere": "Son new wave minimaliste et rebondissant, très rythmique. claquant", "reglages_effets": {}},
    "Wilkenfeld Tal": {"caractere": "Son doux mais expressif, très sensible et technique. rondeur", "reglages_effets": {}},
    "Wimbish Doug": {"caractere": "Son saturé, texturé, très créatif, entre rock, hip-hop et métal. growl", "reglages_effets": {}},
    "Wooten Victor": {"caractere": "Son ultra technique, slappé, inventif, avec une grande musicalité. claquant", "reglages_effets": {}},
    "Young Jennifer": {"caractere": "Son fluide et rapide, très propre, dans un contexte rock instrumental. attaque", "reglages_effets": {}},
    "Zender Stuart": {"caractere": "Son groove élégant et chaleureux, très nuancé. rondeur", "reglages_effets": {}}
}
