basses_avec_type = {
    "Alembic Exploiter / Status Graphite": "active",
    "Alembic Series I": "active",
    "Alembic Stanley Clarke Signature": "active",
    "Ampeg AEB-1": "passive",
    "Aria Pro II SB1000": "active",
    "Carvin Bunny Brunel Signature": "active",
    "Charvel Pro-Mod San Dimas Bass": "passive",
    "Contrebasse acoustique": "passive",
    "Cort A5 Plus SC": "active",
    "Cort Action Bass": "active",
    "Cort GB74JJ": "active",
    "Custom Space Bass": "active",
    "Danelectro 58 Longhorn Bass": "passive",
    "Danelectro Longhorn Bass": "passive",
    "Dean Edge 09": "active",
    "Dean Metalman ML Bass": "active",
    "Dingwall Super J": "passive",
    "ESP LTD B-204": "active",
    "ESP LTD D-4": "active",
    "ESP LTD Surveyor": "active",
    "Epiphone EB-0": "passive",
    "Epiphone Jack Casady Signature Bass": "passive",
    "Epiphone Les Paul Standard Bass": "passive",
    "Epiphone Thunderbird IV": "passive",
    "Epiphone Viola Bass": "passive",
    "Fender Aerodyne Jazz Bass": "passive",
    "Fender Jaguar Bass": "passive",
    "Fender Jazz Bass": "passive",
    "Fender Jazz Bass / Contrebasse": "passive",
    "Fender Jazz Bass Darryl Jones Signature": "passive",
    "Fender Jazz Bass Geddy Lee Signature": "passive",
    "Fender Jazz Bass Marcus Miller Signature": "active",
    "Fender Jazz Bass fretless": "passive",
    "Fender Mark Hoppus Jazz Bass": "passive",
    "Fender Mustang Bass": "passive",
    "Fender Player Jazz Bass": "passive",
    "Fender Player Precision Bass": "passive",
    "Fender Precision Bass": "passive",
    "Fender Precision Bass Mike Dirnt Signature": "passive",
    "Fender Precision Bass Nate Mendel Signature": "passive",
    "Fender Precision Bass Sean Hurley Signature": "passive",
    "Fender Precision Bass Steve Harris Signature": "passive",
    "Fender Precision Bass fretless": "passive",
    "Fodera Emperor": "active",
    "Fodera Imperial": "active",
    "Fodera Monarch": "active",
    "G&L Kiloton": "passive",
    "G&L L-2000": "active",
    "G&L SB-2": "passive",
    "G&L Tribute JB-2": "passive",
    "Gibson EB-3": "passive",
    "Gibson Les Paul Bass": "passive",
    "Gibson RD Artist Bass": "active",
    "Gibson SG Bass": "passive",
    "Gibson Thunderbird": "passive",
    "Gretsch G2220 Junior Jet Bass II": "passive",
    "Gretsch G5442BDC Electromatic Short-Scale Bass": "passive",
    "Harley Benton B-450": "active",
    "Harley Benton JB-75": "passive",
    "Harley Benton PB-50": "passive",
    "Höfner Club Bass": "passive",
    "Höfner Violin Bass": "passive",
    "Ibanez BTB845": "active",
    "Ibanez SR Premium": "active",
    "Ibanez SR300": "active",
    "Ibanez SR500": "active",
    "Ibanez SR700": "active",
    "Ibanez Talman TMB100": "passive",
    "Jackson CBXNT IV": "active",
    "Jackson JS Series Concert Bass": "passive",
    "Ken Smith BSR 5EG": "active",
    "Lakland Skyline 44-02": "active",
    "Lakland USA Series": "active",
    "Mayones Jabba": "active",
    "Modulus Flea Bass": "active",
    "Modulus Quantum": "active",
    "Music Man Bongo": "active",
    "Music Man Cutlass Bass": "active",
    "Music Man Sabre Bass": "active",
    "Music Man Sterling": "active",
    "Music Man StingRay": "active",
    "Music Man StingRay / Chapman Stick": "active",
    "Peavey Cirrus 4": "active",
    "Peavey Millennium BXP": "active",
    "Peavey T-40": "passive",
    "Pedulla MVP": "active",
    "Rickenbacker 4001": "passive",
    "Rickenbacker 4003": "passive",
    "Rickenbacker 4004LK": "active",
    "Sadowsky NYC": "active",
    "Sadowsky Will Lee Signature": "active",
    "Sandberg California VM": "active",
    "Schecter Stiletto Extreme-4": "active",
    "Schecter Stiletto Studio-4": "active",
    "Shergold Modulator Bass": "passive",
    "Spector Euro 4 LX": "active",
    "Squier Affinity Jazz Bass": "passive",
    "Squier Affinity Precision Bass PJ": "passive",
    "Squier Classic Vibe '60s Precision Bass": "passive",
    "Squier Classic Vibe '70s Jazz Bass": "passive",
    "Squier Vintage Modified Jaguar Bass": "passive",
    "Status Graphite KingBass": "active",
    "Sterling Cutlass Bass": "active",
    "Sterling SUB Ray4": "active",
    "Sterling SUB Ray5": "active",
    "Sterling StingRay HH": "active",
    "Sterling StingRay Short Scale": "active",
    "Vigier Arpège": "active",
    "Vigier Passion": "active",
    "Warwick Corvette Standard": "active",
    "Warwick Infinity NT": "active",
    "Warwick Jonas Hellborg Signature": "active",
    "Warwick RockBass Corvette": "active",
    "Warwick Streamer Stage I": "active",
    "Warwick Thumb Bass": "active",
    "Washburn B-20": "passive",
    "Yamaha BB": "passive",
    "Yamaha BB1200S": "passive",
    "Yamaha BB414": "passive",
    "Yamaha BB734A": "active",
    "Yamaha BBNE2": "active",
    "Yamaha BBP34": "passive",
    "Yamaha RBX6JM": "active",
    "Yamaha TRB": "active",
    "Yamaha TRBX174": "passive",
    "Yamaha TRBX504": "active",
    "Zon Hyperbass": "active",
    "Zon Sonus 5": "active"
}
