"""
Liste des bassistes disponibles.
Chaque bassiste est représenté par un dictionnaire contenant :
- "nom" : le nom de famille
- "prenom" : le prénom
- "groupe" : le groupe ou les collaborations associés
"""

bassistes = [
    {"nom": "Alibo", "prenom": "Michel", "groupe": "Sixun"},
    {"nom": "Baroux", "prenom": "Manu", "groupe": "Scène funk/soul"},
    {"nom": "Beggs", "prenom": "Nick", "groupe": "Kajagoogoo, Steven Wilson"},
    {"nom": "Benjelloun", "prenom": "Michaël", "groupe": "Chanson française"},
    {"nom": "Biyong", "prenom": "Franck", "groupe": "Afrobeat"},
    {"nom": "Bisello", "prenom": "Jean", "groupe": "Studio, jazz"},
    {"nom": "Bogert", "prenom": "Tim", "groupe": "Vanilla Fudge"},
    {"nom": "Bona", "prenom": "Richard", "groupe": "Solo, jazz world"},
    {"nom": "Brunel", "prenom": "Bunny", "groupe": "Jazz fusion"},
    {"nom": "Bruce", "prenom": "Jack", "groupe": "Cream"},
    {"nom": "Bussonnet", "prenom": "Philippe", "groupe": "Magma"},
    {"nom": "Cokelaere", "prenom": "Laurent", "groupe": "Johnny Hallyday, Trust"},
    {"nom": "Clayton", "prenom": "Adam", "groupe": "U2"},
    {"nom": "Clarke", "prenom": "Stanley", "groupe": "Return to Forever"},
    {"nom": "Collins", "prenom": "Bootsy", "groupe": "Parliament-Funkadelic"},
    {"nom": "Commerford", "prenom": "Tim", "groupe": "RATM, Audioslave"},
    {"nom": "De Angelis", "prenom": "Victoria", "groupe": "Måneskin"},
    {"nom": "Deacon", "prenom": "John", "groupe": "Queen"},
    {"nom": "Deal", "prenom": "Kim", "groupe": "Pixies"},
    {"nom": "Dirnt", "prenom": "Mike", "groupe": "Green Day"},
    {"nom": "Dorsey", "prenom": "Gail Ann", "groupe": "David Bowie"},
    {"nom": "Dupont", "prenom": "Fred", "groupe": "No One Is Innocent"},
    {"nom": "East", "prenom": "Nathan", "groupe": "Eric Clapton, Phil Collins"},
    {"nom": "Entwistle", "prenom": "John", "groupe": "The Who"},
    {"nom": "Feraud", "prenom": "Hadrien", "groupe": "Solo, jazz fusion"},
    {"nom": "Fiszman", "prenom": "Nicolas", "groupe": "Studio"},
    {"nom": "Fisher", "prenom": "Norwood", "groupe": "Fishbone"},
    {"nom": "Flea", "prenom": "Michael Balzary", "groupe": "Red Hot Chili Peppers"},
    {"nom": "Glover", "prenom": "Roger", "groupe": "Deep Purple"},
    {"nom": "Gordon", "prenom": "Mike", "groupe": "Phish"},
    {"nom": "Harris", "prenom": "Steve", "groupe": "Iron Maiden"},
    {"nom": "Hellborg", "prenom": "Jonas", "groupe": "Solo, jazz fusion"},
    {"nom": "Hoppus", "prenom": "Mark", "groupe": "Blink-182"},
    {"nom": "Hook", "prenom": "Peter", "groupe": "Joy Division, New Order"},
    {"nom": "Hurley", "prenom": "Sean", "groupe": "John Mayer"},
    {"nom": "Jamerson", "prenom": "James", "groupe": "The Funk Brothers (Motown)"},
    {"nom": "Jones", "prenom": "Darryl", "groupe": "Rolling Stones, Miles Davis"},
    {"nom": "Kajdan", "prenom": "Jean-Michel", "groupe": "Solo, studio"},
    {"nom": "Kanal", "prenom": "Tony", "groupe": "No Doubt"},
    {"nom": "Kaye", "prenom": "Carol", "groupe": "The Wrecking Crew"},
    {"nom": "Kilmister", "prenom": "Lemmy", "groupe": "Motörhead"},
    {"nom": "Kumalo", "prenom": "Bakithi", "groupe": "Paul Simon"},
    {"nom": "Labaye", "prenom": "Romain", "groupe": "Scott Henderson"},
    {"nom": "Lee", "prenom": "Geddy", "groupe": "Rush"},
    {"nom": "Lee", "prenom": "Will", "groupe": "Letterman Band"},
    {"nom": "Lesh", "prenom": "Phil", "groupe": "Grateful Dead"},
    {"nom": "Levin", "prenom": "Tony", "groupe": "King Crimson, Peter Gabriel"},
    {"nom": "Lynott", "prenom": "Phil", "groupe": "Thin Lizzy"},
    {"nom": "Maby", "prenom": "Graham", "groupe": "Joe Jackson"},
    {"nom": "Manring", "prenom": "Michael", "groupe": "Solo, expérimental"},
    {"nom": "Mbappé", "prenom": "Etienne", "groupe": "John McLaughlin"},
    {"nom": "McCartney", "prenom": "Paul", "groupe": "The Beatles"},
    {"nom": "McVie", "prenom": "John", "groupe": "Fleetwood Mac"},
    {"nom": "Mendel", "prenom": "Nate", "groupe": "Foo Fighters"},
    {"nom": "Mendez", "prenom": "Martin", "groupe": "Opeth"},
    {"nom": "Mienniel", "prenom": "Jocelyn", "groupe": "Électro-jazz"},
    {"nom": "Miller", "prenom": "Marcus", "groupe": "Miles Davis, solo"},
    {"nom": "Morel", "prenom": "Jean-Philippe", "groupe": "Papanosh, ONJ"},
    {"nom": "Moutin", "prenom": "Louis", "groupe": "Moutin Reunion Quartet"},
    {"nom": "Mulot", "prenom": "Pascal", "groupe": "Rock metal"},
    {"nom": "Myung", "prenom": "John", "groupe": "Dream Theater"},
    {"nom": "Ndegeocello", "prenom": "Meshell", "groupe": "Solo"},
    {"nom": "Newsted", "prenom": "Jason", "groupe": "Metallica"},
    {"nom": "Paganotti", "prenom": "Bernard", "groupe": "Magma, Weidorje"},
    {"nom": "Palladino", "prenom": "Pino", "groupe": "The Who, John Mayer"},
    {"nom": "Pastorius", "prenom": "Jaco", "groupe": "Weather Report"},
    {"nom": "Prestia", "prenom": "Rocco", "groupe": "Tower of Power"},
    {"nom": "Ramone", "prenom": "Dee Dee", "groupe": "Ramones"},
    {"nom": "Rossi", "prenom": "Stéphan", "groupe": "Studio"},
    {"nom": "Rostand", "prenom": "Alexis", "groupe": "L'impératrice"},
    {"nom": "Rutherford", "prenom": "Mike", "groupe": "Genesis"},
    {"nom": "Sabal-Lecco", "prenom": "Armand", "groupe": "Sting, studio"},
    {"nom": "Sklar", "prenom": "Leland", "groupe": "Phil Collins, studio"},
    {"nom": "Spalding", "prenom": "Esperanza", "groupe": "Solo, jazz"},
    {"nom": "Squire", "prenom": "Chris", "groupe": "Yes"},
    {"nom": "Taylor", "prenom": "John", "groupe": "Duran Duran"},
    {"nom": "Texier", "prenom": "Henri", "groupe": "Jazz français"},
    {"nom": "Vernerey", "prenom": "Laurent", "groupe": "Studio (Pagny, Hallyday...)"},
    {"nom": "Waters", "prenom": "Roger", "groupe": "Pink Floyd"},
    {"nom": "Weymouth", "prenom": "Tina", "groupe": "Talking Heads"},
    {"nom": "Wilkenfeld", "prenom": "Tal", "groupe": "Jeff Beck"},
    {"nom": "Wimbish", "prenom": "Doug", "groupe": "Living Colour"},
    {"nom": "Wooten", "prenom": "Victor", "groupe": "Béla Fleck and the Flecktones"},
    {"nom": "Young", "prenom": "Jennifer", "groupe": "Travis Larson Band"}
]
