# liste_basses_completes.py

basses_uniques = [
    "Alembic Exploiter / Status Graphite",
    "Alembic Series I",
    "Alembic Stanley Clarke Signature",
    "Ampeg AEB-1",
    "Aria Pro II SB1000",
    "Carvin Bunny Brunel Signature",
    "Charvel Pro-Mod San Dimas Bass",
    "Contrebasse acoustique",
    "Cort A5 Plus SC",
    "Cort Action Bass",
    "Cort GB74JJ",
    "Custom Space Bass",
    "Danelectro 58 Longhorn Bass",
    "Danelectro Longhorn Bass",
    "Dean Edge 09",
    "Dean Metalman ML Bass",
    "Dingwall Super J",
    "ESP LTD B-204",
    "ESP LTD D-4",
    "ESP LTD Surveyor",
    "Epiphone EB-0",
    "Epiphone Jack Casady Signature Bass",
    "Epiphone Les Paul Standard Bass",
    "Epiphone Thunderbird IV",
    "Epiphone Viola Bass",
    "Fender Aerodyne Jazz Bass",
    "Fender Jaguar Bass",
    "Fender Jazz Bass",
    "Fender Jazz Bass / Contrebasse",
    "Fender Jazz Bass Darryl Jones Signature",
    "Fender Jazz Bass Geddy Lee Signature",
    "Fender Jazz Bass Marcus Miller Signature",
    "Fender Jazz Bass fretless",
    "Fender Mark Hoppus Jazz Bass",
    "Fender Mustang Bass",
    "Fender Player Jazz Bass",
    "Fender Player Precision Bass",
    "Fender Precision Bass",
    "Fender Precision Bass Mike Dirnt Signature",
    "Fender Precision Bass Nate Mendel Signature",
    "Fender Precision Bass Sean Hurley Signature",
    "Fender Precision Bass Steve Harris Signature",
    "Fender Precision Bass fretless",
    "Fodera Emperor",
    "Fodera Imperial",
    "Fodera Monarch",
    "G&L Kiloton",
    "G&L L-2000",
    "G&L SB-2",
    "G&L Tribute JB-2",
    "Gibson EB-3",
    "Gibson Les Paul Bass",
    "Gibson RD Artist Bass",
    "Gibson SG Bass",
    "Gibson Thunderbird",
    "Gretsch G2220 Junior Jet Bass II",
    "Gretsch G5442BDC Electromatic Short-Scale Bass",
    "Harley Benton B-450",
    "Harley Benton JB-75",
    "Harley Benton PB-50",
    "Höfner Club Bass",
    "Höfner Violin Bass",
    "Ibanez BTB845",
    "Ibanez SR Premium",
    "Ibanez SR300",
    "Ibanez SR500",
    "Ibanez SR700",
    "Ibanez Talman TMB100",
    "Jackson CBXNT IV",
    "Jackson JS Series Concert Bass",
    "Ken Smith BSR 5EG",
    "Lakland Skyline 44-02",
    "Lakland USA Series",
    "Mayones Jabba",
    "Modulus Flea Bass",
    "Modulus Quantum",
    "Music Man Bongo",
    "Music Man Cutlass Bass",
    "Music Man Sabre Bass",
    "Music Man Sterling",
    "Music Man StingRay",
    "Music Man StingRay / Chapman Stick",
    "Peavey Cirrus 4",
    "Peavey Millennium BXP",
    "Peavey T-40",
    "Pedulla MVP",
    "Rickenbacker 4001",
    "Rickenbacker 4003",
    "Rickenbacker 4004LK",
    "Sadowsky NYC",
    "Sadowsky Will Lee Signature",
    "Sandberg California VM",
    "Schecter Stiletto Extreme-4",
    "Schecter Stiletto Studio-4",
    "Shergold Modulator Bass",
    "Spector Euro 4 LX",
    "Squier Affinity Jazz Bass",
    "Squier Affinity Precision Bass PJ",
    "Squier Classic Vibe '60s Precision Bass",
    "Squier Classic Vibe '70s Jazz Bass",
    "Squier Vintage Modified Jaguar Bass",
    "Status Graphite KingBass",
    "Sterling Cutlass Bass",
    "Sterling SUB Ray4",
    "Sterling SUB Ray5",
    "Sterling StingRay HH",
    "Sterling StingRay Short Scale",
    "Vigier Arpège",
    "Vigier Passion",
    "Warwick Corvette Standard",
    "Warwick Infinity NT",
    "Warwick Jonas Hellborg Signature",
    "Warwick RockBass Corvette",
    "Warwick Streamer Stage I",
    "Warwick Thumb Bass",
    "Washburn B-20",
    "Yamaha BB",
    "Yamaha BB1200S",
    "Yamaha BB414",
    "Yamaha BB734A",
    "Yamaha BBNE2",
    "Yamaha BBP34",
    "Yamaha RBX6JM",
    "Yamaha TRB",
    "Yamaha TRBX174",
    "Yamaha TRBX504",
    "Zon Hyperbass",
    "Zon Sonus 5"
]

