"""
Liste complète des amplis pour basse.
Chaque élément est une chaîne représentant le modèle d'un ampli.
"""

amplis_basse = [
    "Aguilar DB 751",
    "Aguilar Tone Hammer 500",
    "Ampeg B-15N",
    "Ampeg Micro VR",
    "Ampeg PF-500",
    "Ampeg SVT-2 Pro",
    "Ampeg SVT-3 Pro",
    "Ampeg SVT-4 Pro",
    "Ampeg SVT-CL",
    "Ampeg SVT-VR",
    "Ampeg V-4B",
    "Ashdown ABM 500 EVO IV",
    "Ashdown MAG 300",
    "Ashdown Rootmaster RM-500",
    "Chillamp Alpha",
    "Chillamp Bêta",
    "Chillamp Delta",
    "Darkglass Alpha-Omega 900",
    "Darkglass Microtubes 500",
    "Darkglass Microtubes 900 v2",
    "EBS HD360",
    "EBS Reidmar 750",
    "Eden WT800",
    "Fender Bassman 100T",
    "Fender Bassman 500",
    "Fender Rumble 100",
    "Fender Rumble 200",
    "Fender Rumble 500",
    "Gallien-Krueger 1001RB",
    "Gallien-Krueger 2001RB",
    "Gallien-Krueger MB500",
    "Gallien-Krueger MB800",
    "Gallien-Krueger Fusion 550",
    "Genz-Benz Shuttle 6.2",
    "Genz-Benz Streamliner 600",
    "Genz-Benz Streamliner STM-600",
    "Glockenklang Blue Soul",
    "Glockenklang Heart-Rock II",
    "GR Bass One 800",
    "Hartke HA3500",
    "Hartke LH500",
    "Hartke TX600",
    "Markbass Little Mark II",
    "Markbass Little Mark III",
    "Markbass Little Mark Vintage",
    "Markbass TTE 500 Randy Jackson",
    "Mesa Subway D-800",
    "Mesa Subway WD-800",
    "Mesa Boogie M6 Carbine",
    "Mesa Boogie M9 Carbine",
    "Mesa Boogie Big Block 750",
    "Orange AD200B MK3",
    "Orange OB1-500",
    "Orange Terror Bass 500",
    "Peavey Tour 700",
    "Peavey Max 300",
    "Phil Jones Bass BP-800",
    "Quilter Bass Block 800",
    "TecAmp Puma 500",
    "Trace Elliot ELF",
    "Trace Elliot AH600",
    "Traynor YBA200",
    "Trickfish Bullhead .5K",
    "Warwick LWA 1000"
]
