"""
Liste complète des effets pour basse.
Chaque élément est une chaîne représentant un effet ou un processeur pour basse.
"""

effets_basse = [
    "Acoustic Simulator (Boss AC-3)",
    "Auto Wah (EBS BassIQ)",
    "Bass Chorus (Boss CEB-3)",
    "Bass Compressor (MXR M87)",
    "Bass Delay (MXR Carbon Copy Deluxe)",
    "Bass Distortion (Darkglass Microtubes B3K)",
    "Bass Envelope Filter (3Leaf Audio Proton)",
    "Bass Equalizer (Boss GEB-7)",
    "Bass Fuzz (Way Huge Pork Loin)",
    "Bass Limiter (Boss LMB-3)",
    "Bass Octaver (EBS OctaBass)",
    "Bass Overdrive (Darkglass Vintage Microtubes)",
    "Bass Phaser (MXR Phase 90)",
    "Bass Preamp (Aguilar Tone Hammer)",
    "Bass Synth (Boss SYB-5)",
    "Bit Crusher (Mooer LoFi Machine)",
    "Cab Simulator (Two Notes Torpedo CAB M+)",
    "Chorus (Electro-Harmonix Small Clone)",
    "Clean Boost (Xotic RC Booster)",
    "Compressor (Keeley Bassist Limiting Amplifier)",
    "Compressor ("Darkglass Hyper Luminal)",
    "Crossover (Ashdown Sub Octave Plus)",
    "Delay (TC Electronic Flashback)",
    "Detuner (Digitech Drop)",
    "Di Box Active (Radial J48)",
    "Di Box Passive (Radial ProDI)",
    "Distortion (ProCo Rat 2)",
    "Dual Band Compressor (Empress Compressor MKII)",
    "Dual Drive (Darkglass Duality)",
    "Dynamic Filter (EHX Enigma Qballs)",
    "Echo (Boss RE-20 Space Echo)",
    "Enhancer (BBE Sonic Maximizer)",
    "Envelope Filter (Electro-Harmonix Q-Tron)",
    "Equalizer Parametric (Source Audio EQ2)",
    "Equalizer Graphique (Boss GEB-7)",
    "Exciter (Aphex Bass Xciter)",
    "Expression Pedal (Mission Engineering EP1)",
    "Filter Synth (Markbass Super Synth)",
    "Flanger (MXR M117R Flanger)",
    "Fretless Simulator (Zoom B3n)",
    "Fuzz (ZVex Woolly Mammoth)",
    "Gate (ISP Decimator II)",
    "Graphic EQ (MXR 10-Band EQ)",
    "Harmonizer (Eventide PitchFactor)",
    "Limiter (Boss LMB-3)",
    "Looper (TC Electronic Ditto Looper)",
    "Low Pass Filter (Moogerfooger MF-101)",
    "LFO Modulator (Chase Bliss Warped Vinyl)",
    "Mid Boost (Aguilar OBP-1)",
    "Mixer Blend (Xotic X-Blender)",
    "Modulator (Strymon Mobius)",
    "Multi Band Compressor (tc electronic SpectraComp)",
    "Multi Chorus (Zoom MS-60B)",
    "Multi Delay (Line 6 DL4 MkII)",
    "Multi Effect (Line 6 HX Stomp)",
    "Noise Gate (Boss NS-2)",
    "Octaver (Electro-Harmonix POG2)",
    "Overdrive (Fulltone Bass-Drive MOSFET)",
    "Parametric EQ (Empress ParaEQ MKII)",
    "Phaser (MXR Phase 90)",
    "Pitch Shifter (Digitech Whammy DT)",
    "Preamp (Aguilar DB 925)",
    "Reverb (TC Electronic Hall of Fame 2)",
    "Ring Modulator (Moogerfooger MF-102)",
    "Rotary Speaker (Neo Ventilator II)",
    "Sampler (Boss RC-5)",
    "Saturation (Darkglass Harmonic Booster)",
    "Send Return Loop (Boss LS-2)",
    "Signal Splitter (Radial BigShot ABY)",
    "Slap Enhancer (Zoom B3n Slap Patch)",
    "Soft Clipping (Way Huge Red Llama)",
    "Spring Reverb (Catalinbread Topanga)",
    "Stomp Compressor (MXR Dyna Comp)",
    "Sub Octave Generator (EHX Nano POG)",
    "Sustain (Boss CS-3)",
    "Synth Bass (Markbass Super Synth)",
    "Tape Echo (Strymon El Capistan)",
    "Tremolo (EHX Stereo Pulsar)",
    "Tube Compressor (EBS Multicomp)",
    "Tube Distortion (EBS ValveDrive DI)",
    "Tube Preamp (EBS Microbass 3)",
    "Tuner (Boss TU-3)",
    "UniVibe (Dunlop Uni-Vibe UV1)",
    "Vibrato (TC Electronic Shaker)",
    "Vintage Overdrive (Ibanez TS9B)",
    "Volume Pedal (Ernie Ball VP Jr)",
    "Wave Shaper (Source Audio Ultrawave)",
    "Wah (Dunlop 105Q Bass Wah)",
    "X-Over Drive (Iron Ether Oxide)",
    "Zipper Filter (EHX Zipper)",
    "Zoom Bass Multi FX (Zoom B3n)",
    "3-Band EQ (MXR M81)",
    "5-Band EQ (MXR M75)",
    "Amp Simulator (Tech 21 SansAmp Bass Driver DI)",
    "Analog Delay (Ibanez AD9)",
    "Bass Enhancer (Behringer BLE100)",
    "Clean Buffer (TC Electronic Bonafide)",
    "Color Booster (Xotic EP Booster)",
    "Digital Delay (Boss DD-7)",
    "Drive + EQ (Aguilar Agro)",
    "Drive Blend (MXR M85 Bass Distortion)",
    "Dual Octaver (EHX POG2)",
    "FX Loop Switcher (Boss ES-5)",
    "High Cut Filter (Darkglass Tone Capsule)",
    "Preamp + DI (Tech 21 VT Bass DI)",
    "Resonant Filter (Iron Ether Xerograph Deluxe)",
    "Stack Simulator (Line 6 Helix)"
]
